'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Alcohol", [
      { type: "SCOTCH WHISKY", brandStyle: "GLENLIVET/18yr", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 700, gramsPerOunce: 12 },
      { type: "SCOTCH WHISKY", brandStyle: "GLENLIVET/12yr", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 900, gramsPerOunce: 12.5 },
      { type: "SCOTCH WHISKY", brandStyle: "GLENLIVET/12yr", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 685, gramsPerOunce: 12.5 },
      { type: "SCOTCH WHISKY", brandStyle:  "JOHNNY WALKER/BLACK LABEL", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 873, gramsPerOunce: 13.3 },
      { type: "SCOTCH WHISKY", brandStyle:  "LAPHROIG/ISLAY", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 617, gramsPerOunce: 11 },
      { type: "IRISH WHISKY", brandStyle:  "JAMESON/IRISH", sizeML: 1000, sizeOZ: 33.81, emptyBottleWeight: 673, gramsPerOunce: 10 },
      { type: "JAPANESE WHISKY", brandStyle: "CHICHIBU/ICHIRO'S MALT AND GRAIN/700", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 603, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle:  "CHUGOKU JO/TOGOUCHI", sizeML: 750, sizeOZ: 25.36, emptyBottleWeight: 569, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle:  "NIKKA/COFFEY GRAIN", sizeML: 750, sizeOZ: 25.36, emptyBottleWeight: 542, gramsPerOunce: 13 },
      { type: "JAPANESE WHISKY", brandStyle:  "NIKKA/COFFEY MALT", sizeML: 750, sizeOZ: 25.36, emptyBottleWeight: 586, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle:  "NIKKA/MIYAGIKYO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 588, gramsPerOunce: 14 },
      { type: "JAPANESE WHISKY", brandStyle:  "NIKKA/TAKETSURU", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 602, gramsPerOunce: 15.5 },
      { type: "JAPANESE WHISKY", brandStyle:  "OHISHI/SHERRY CASK", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 712, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle: "SUNTORY/HAKSHU 12YR", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 645, gramsPerOunce: 15 },
      { type: "JAPANESE WHISKY", brandStyle:  "SUNTORY/HIBIKI NON VINTAGE", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 643, gramsPerOunce: 13 },
      { type: "JAPANESE WHISKY", brandStyle:  "SUNTORY/TOKI", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 666, gramsPerOunce: 15 },
      { type: "JAPANESE WHISKY", brandStyle: "SUNTORY/YAMAZAKI 12YR", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 696, gramsPerOunce: 16 },
      { type: "JAPANESE WHISKY", brandStyle:  "SUNTORY/YAMAZAKI NON VINTAGE", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 587, gramsPerOunce: 12.5 },
      { type: "AMERICAN WHISKY", brandStyle:  "JACK DANIEL'S/TENNESSEE", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 845, gramsPerOunce: 12 },
      { type: "AMERICAN WHISKY", brandStyle:  "JIM BEAN/BOURBON", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 880, gramsPerOunce: 14 },
      { type: "AMERICAN WHISKY", brandStyle:  "KNOB CREEK/BOURBON", sizeML: 1000, sizeOZ: 33.81, emptyBottleWeight: 864, gramsPerOunce: 10 },
      { type: "AMERICAN WHISKY", brandStyle:  "MAKER'S MARK/BOURBON", sizeML: 1000, sizeOZ: 33.81, emptyBottleWeight: 903, gramsPerOunce: 12 },
      { type: "AMERICAN WHISKY", brandStyle:  "OLD OVERHOLDT/RYE", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 765, gramsPerOunce: 13 },
      { type: "AMERICAN WHISKY", brandStyle:  "REBEL YELL/BOURBON", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 700, gramsPerOunce: 17 },
      { type: "AMERICAN WHISKY", brandStyle:  "WESTLAND PEATED/AMERICAN", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 659, gramsPerOunce: 12.5 },
      { type: "AMERICAN WHISKY", brandStyle:  "BASIL HAYDEN'S/BOURBON", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 597, gramsPerOunce: 14 },
      { type: "AMERICAN WHISKY", brandStyle:  "YELLOWSTONE/BOURBON", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 777, gramsPerOunce: 15 },
      { type: "AMERICAN WHISKY", brandStyle:  "BULLEIT/BOURBON", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 679, gramsPerOunce: 14 },
      { type: "AMERICAN WHISKY", brandStyle:  "BULLEIT/RYE", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 665, gramsPerOunce: 13 },
      { type: "COGNAC", brandStyle:  "REMY MARTIN/VSOP", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 643, gramsPerOunce: 12 },
      { type: "COGNAC", brandStyle:  "REMY MARTIN/XO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 700, gramsPerOunce: 13 },
      { type: "COGNAC", brandStyle:  "COURVOISIER/VSOP", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 590, gramsPerOunce: 12 },
      { type: "GIN", brandStyle:  "BEEFEATER/LONDON DRY", sizeML: 750, sizeOZ: 25.36, emptyBottleWeight: 612, gramsPerOunce: 13 },
      { type: "GIN", brandStyle:  "BOMBAY SAPHIRE/BOTANICAL", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 615, gramsPerOunce: 12 },
      { type: "GIN", brandStyle:  "MARTIN MILLERS/NAVY STRENGTH", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 667, gramsPerOunce: 13 },
      { type: "GIN", brandStyle:  "HENDRICKS/BOTANICAL", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 700, gramsPerOunce: 12.5 },
      { type: "GIN", brandStyle:  "TANQUERAY/LONDON DRY", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 708, gramsPerOunce: 13 },
      { type: "GIN", brandStyle:  "GORDONS/LONDON DRY", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 645, gramsPerOunce: 12 },
      { type: "GIN", brandStyle:  "PLYMOUTH/PLYMOUTH", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 734, gramsPerOunce: 15 },
      { type: "RUM", brandStyle:  "BACARDI/LIGHT", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 749, gramsPerOunce: 14 },
      { type: "RUM", brandStyle:  "GOSLINGS/DARK", sizeML: 750, sizeOZ:  25.36 , emptyBottleWeight: 698, gramsPerOunce: 12 },
      { type: "RUM", brandStyle: "RON ZACAPA/23 YEAR CENTENARIO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 712, gramsPerOunce: 14 },
      { type: "RUM", brandStyle: "ZAYA/12YR", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 815, gramsPerOunce: 15 },
      { type: "VODKA", brandStyle:  "ABSOLUTE/PLAIN", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 667, gramsPerOunce: 12 },
      { type: "VODKA", brandStyle:  "CHOPIN/PLAIN", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 645, gramsPerOunce: 12.5 },
      { type: "VODKA", brandStyle:  "GREY GOOSE/PLAIN", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 623, gramsPerOunce: 12 },
      { type: "VODKA", brandStyle:  "HANGAR ONE/PLAIN", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 543, gramsPerOunce: 13 },
      { type: "VODKA", brandStyle:  "STOLICHNAYA/PLAIN", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 703, gramsPerOunce: 13 },
      { type: "VODKA", brandStyle:  "KETEL ONE/PLAIN", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 687, gramsPerOunce: 13 },
      { type: "VODKA", brandStyle:  "TITO'S/PLAIN", sizeML: 1000, sizeOZ: 33.81, emptyBottleWeight: 702, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle:  "SAUZA/BLANCO", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 650, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle:  "SAUZA/REPOSADO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 650, gramsPerOunce: 14 },
      { type: "TEQUILA", brandStyle:  "SAUZA/ANEJO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 650, gramsPerOunce: 14.5 },
      { type: "TEQUILA", brandStyle:  "SAUZA/HORNITOS", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 650, gramsPerOunce: 12.5 },
      { type: "TEQUILA", brandStyle:  "FORTALEZA/REPOSADO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 668, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle:  "FORTALEZA/BLANCO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 668, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle:  "FORTALEZA/ANEJO", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 668, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle:  "DON JULIO/BLANCO", sizeML: 750, sizeOZ: 25.36, emptyBottleWeight: 637, gramsPerOunce: 14 },
      { type: "TEQUILA", brandStyle:  "DON JULIO/REPOSADO", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 637, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle:  "DON JULIO/ANEJO", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 637, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle: "DON JULIO/1942", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 712, gramsPerOunce: 15 },
      { type: "TEQUILA", brandStyle:  "CASA NOBLE/BLANCO", sizeML: 1000, sizeOZ: 33.81 , emptyBottleWeight: 665, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle:  "CASA NOBLE/REPOSADO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 665, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle:  "CASA NOBLE/ANEJO", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 665, gramsPerOunce: 15 },
      { type: "AMARO", brandStyle:  "FERNET BRANCA/ORIGINAL", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 605, gramsPerOunce: 14 },
      { type: "AMARO", brandStyle:  "AMARGO VALET/ORIGINAL", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 700, gramsPerOunce: 15 },
      { type: "AMARO", brandStyle:  "AMARO NONINO/ORIGINAL", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 703, gramsPerOunce: 14 },
      { type: "AMARO", brandStyle:  "CYNAR/ORIGINAL", sizeML: 750, sizeOZ: 25.36 , emptyBottleWeight: 688, gramsPerOunce: 16 },        
    ], {});
  },

  down: (queryInterface) => {
    return queryInterface.bulkDelete("Alcohol", null, {});
  }
};
