'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Alcohol", [
      { type: "SCOTCH WHISKY", brandStyle: "GLENLIVET/18yr", bottleSize: 700, gramsPerOunce: 12 },
      { type: "SCOTCH WHISKY", brandStyle: "GLENLIVET/12yr", bottleSize: 900, gramsPerOunce: 15 },
      { type: "SCOTCH WHISKY", brandStyle: "GLENLIVET/12yr", bottleSize: 685, gramsPerOunce: 12.5 },
      { type: "SCOTCH WHISKY", brandStyle: "JOHNNY WALKER/BLACK LABEL", bottleSize: 873, gramsPerOunce: 13.3 },
      { type: "SCOTCH WHISKY", brandStyle: "LAPHROIG/ISLAY", bottleSize: 617, gramsPerOunce: 11 },
      { type: "IRISH WHISKY", brandStyle: "JAMESON/IRISH", bottleSize: 673, gramsPerOunce: 10 },
      { type: "JAPANESE WHISKY", brandStyle: "CHICHIBU/ICHIRO'S MALT AND GRAIN/700ml", bottleSize: 603, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle: "CHUGOKU JOZO/TOGOUCHI", bottleSize: 569, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle: "NIKKA/COFFEY GRAIN", bottleSize: 542, gramsPerOunce: 13 },
      { type: "JAPANESE WHISKY", brandStyle: "NIKKA/COFFEY MALT", bottleSize: 586, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle: "NIKKA/MIYAGIKYO", bottleSize: 588, gramsPerOunce: 14 },
      { type: "JAPANESE WHISKY", brandStyle: "NIKKA/TAKETSURU", bottleSize: 602, gramsPerOunce: 15.5 },
      { type: "JAPANESE WHISKY", brandStyle: "OHISHI/SHERRY CASK", bottleSize: 712, gramsPerOunce: 12 },
      { type: "JAPANESE WHISKY", brandStyle: "SUNTORY/HAKSHU 12YR", bottleSize: 645, gramsPerOunce: 15 },
      { type: "JAPANESE WHISKY", brandStyle: "SUNTORY/HIBIKI NON VINTAGE", bottleSize: 643, gramsPerOunce: 13 },
      { type: "JAPANESE WHISKY", brandStyle: "SUNTORY/TOKI", bottleSize: 666, gramsPerOunce: 15 },
      { type: "JAPANESE WHISKY", brandStyle: "SUNTORY/YAMAZAKI 12YR", bottleSize: 696, gramsPerOunce: 16 },
      { type: "JAPANESE WHISKY", brandStyle: "SUNTORY/YAMAZAKI NON VINTAGE", bottleSize: 587, gramsPerOunce: 12.5 },
      { type: "AMERICAN WHISKY", brandStyle: "JACK DANIEL'S/TENNESSEE", bottleSize: 845, gramsPerOunce: 12 },
      { type: "AMERICAN WHISKY", brandStyle: "JIM BEAN/BOURBON", bottleSize: 880, gramsPerOunce: 14 },
      { type: "AMERICAN WHISKY", brandStyle: "KNOB CREEK/BOURBON", bottleSize: 864, gramsPerOunce: 10 },
      { type: "AMERICAN WHISKY", brandStyle: "MAKER'S MARK/BOURBON", bottleSize: 903, gramsPerOunce: 12 },
      { type: "AMERICAN WHISKY", brandStyle: "OLD OVERHOLDT/RYE", bottleSize: 765, gramsPerOunce: 13 },
      { type: "AMERICAN WHISKY", brandStyle: "REBEL YELL/BOURBON", bottleSize: 700, gramsPerOunce: 17 },
      { type: "AMERICAN WHISKY", brandStyle: "WESTLAND PEATED/AMERICAN", bottleSize: 659, gramsPerOunce: 12.5 },
      { type: "AMERICAN WHISKY", brandStyle: "BASIL HAYDEN'S/BOURBON", bottleSize: 597, gramsPerOunce: 14 },
      { type: "AMERICAN WHISKY", brandStyle: "YELLOWSTONE/BOURBON", bottleSize: 777, gramsPerOunce: 15 },
      { type: "AMERICAN WHISKY", brandStyle: "BULLEIT/BOURBON", bottleSize: 679, gramsPerOunce: 14 },
      { type: "AMERICAN WHISKY", brandStyle: "BULLEIT/RYE", bottleSize: 665, gramsPerOunce: 13 },
      { type: "COGNAC", brandStyle: "REMY MARTIN/VSOP", bottleSize: 643, gramsPerOunce: 12 },
      { type: "COGNAC", brandStyle: "REMY MARTIN/XO", bottleSize: 700, gramsPerOunce: 13 },
      { type: "COGNAC", brandStyle: "COURVOISIER/VSOP", bottleSize: 590, gramsPerOunce: 12 },
      { type: "GIN", brandStyle: "BEEFEATER/LONDON DRY", bottleSize: 612, gramsPerOunce: 13 },
      { type: "GIN", brandStyle: "BOMBAY SAPHIRE/BOTANICAL", bottleSize: 615, gramsPerOunce: 12 },
      { type: "GIN", brandStyle: "MARTIN MILLERS/NAVY STRENGTH", bottleSize: 667, gramsPerOunce: 13 },
      { type: "GIN", brandStyle: "HENDRICKS/BOTANICAL", bottleSize: 700, gramsPerOunce: 12.5 },
      { type: "GIN", brandStyle: "TANQUERAY/LONDON DRY", bottleSize: 708, gramsPerOunce: 13 },
      { type: "GIN", brandStyle: "GORDONS/LONDON DRY", bottleSize: 645, gramsPerOunce: 12 },
      { type: "GIN", brandStyle: "PLYMOUTH/PLYMOUTH", bottleSize: 734, gramsPerOunce: 15 },
      { type: "RUM", brandStyle: "BACARDI/LIGHT", bottleSize: 749, gramsPerOunce: 14 },
      { type: "RUM", brandStyle: "GOSLINGS/DARK", bottleSize: 698, gramsPerOunce: 12 },
      { type: "RUM", brandStyle: "RON ZACAPA/23 YEAR CENTENARIO", bottleSize: 712, gramsPerOunce: 14 },
      { type: "RUM", brandStyle: "ZAYA/12YR", bottleSize: 815, gramsPerOunce: 15 },
      { type: "VODKA", brandStyle: "ABSOLUTE/PLAIN", bottleSize: 667, gramsPerOunce: 12 },
      { type: "VODKA", brandStyle: "CHOPIN/PLAIN", bottleSize: 645, gramsPerOunce: 12 / 5 },
      { type: "VODKA", brandStyle: "GREY GOOSE/PLAIN", bottleSize: 623, gramsPerOunce: 12 },
      { type: "VODKA", brandStyle: "HANGAR ONE/PLAIN", bottleSize: 543, gramsPerOunce: 13 },
      { type: "VODKA", brandStyle: "STOLICHNAYA/PLAIN", bottleSize: 703, gramsPerOunce: 13 },
      { type: "VODKA", brandStyle: "KETEL ONE/PLAIN", bottleSize: 687, gramsPerOunce: 13 },
      { type: "VODKA", brandStyle: "TITO'S/PLAIN", bottleSize: 702, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle: "SAUZA/BLANCO", bottleSize: 650, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle: "SAUZA/REPOSADO", bottleSize: 650, gramsPerOunce: 14 },
      { type: "TEQUILA", brandStyle: "SAUZA/ANEJO", bottleSize: 650, gramsPerOunce: 14.5 },
      { type: "TEQUILA", brandStyle: "SAUZA/HORNITOS", bottleSize: 650, gramsPerOunce: 12.5 },
      { type: "TEQUILA", brandStyle: "FORTALEZA/REPOSADO", bottleSize: 668, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle: "FORTALEZA/BLANCO", bottleSize: 668, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle: "FORTALEZA/ANEJO", bottleSize: 668, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle: "DON JULIO/BLANCO", bottleSize: 637, gramsPerOunce: 14 },
      { type: "TEQUILA", brandStyle: "DON JULIO/REPOSADO", bottleSize: 637, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle: "DON JULIO/ANEJO", bottleSize: 637, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle: "DON JULIO/1942", bottleSize: 712, gramsPerOunce: 15 },
      { type: "TEQUILA", brandStyle: "CASA NOBLE/BLANCO", bottleSize: 665, gramsPerOunce: 12 },
      { type: "TEQUILA", brandStyle: "CASA NOBLE/REPOSADO", bottleSize: 665, gramsPerOunce: 13 },
      { type: "TEQUILA", brandStyle: "CASA NOBLE/ANEJO", bottleSize: 665, gramsPerOunce: 15 },
      { type: "AMARO", brandStyle: "FERNET BRANCA/ORIGINAL", bottleSize: 605, gramsPerOunce: 14 },
      { type: "AMARO", brandStyle: "AMARGO VALET/ORIGINAL", bottleSize: 700, gramsPerOunce: 15 },
      { type: "AMARO", brandStyle: "AMARO NONINO/ORIGINAL", bottleSize: 703, gramsPerOunce: 14 },
      { type: "AMARO", brandStyle: "CYNAR/ORIGINAL", bottleSize: 688, gramsPerOunce: 16 },
    ], {});
  },

  down: (queryInterface) => {
    return queryInterface.bulkDelete("Alcohol", null, {});
  }
};
